SCREEN_SIZE = (1200, 900)
ICON = 'Lobster.png'
CAPTION = 'Lobster Remake'
FPS = 60
TILE_SIZE = 96
IMAGE_PATH = "assets/images"
MAP_PATH = "assets/maps"
MUSIC_PATH = "assets/music"
SOUND_PATH = "assets/sounds"

SQUARE = 'square'
CIRCLE = 'circle'
SHAPES = [SQUARE, CIRCLE]

#
PARTICLE_UPDATE_RADIUS = 12

#
SELF_PREFIX = "self"
OTHER_PREFIX = "other"

#
MAX_CAMERA_SCALE = 1.5
MIN_CAMERA_SCALE = 1

#
INTERACT_RANGE = int(TILE_SIZE // 2)

#
ITEM_IMAGE_SIZE = 32

# particle attributes
DEFAULT_DISPLAY_PRIORITY = 0
DEFAULT_PARTICLE_TEXTURE = "Lobster_64.png"
DEFAULT_PARTICLE_DISPLAY = "particle"  # used while not reading data from map

#
DEFAULT_SPEED = 250

# Living interface
DEFAULT_HEALTH = 100
DEFAULT_MAX_HEALTH = 100
DEFAULT_HEALTH_REGEN = 10
DEFAULT_DEATH_CONDITION = "( health <= 0 )"

# Staminaized interface
DEFAULT_STAMINA = 100
DEFAULT_MAX_STAMINA = 100
DEFAULT_STAMINA_REGEN = 25
DEFAULT_ACTION_TIMER = 1  # Actions that last 1 frame

# Manaized interface
DEFAULT_MANA = 100
DEFAULT_MAX_MANA = 100
DEFAULT_MANA_REGEN = 20

# StandardAttacks interface
DEFAULT_ATTACK_DAMAGE = 40
DEFAULT_ATTACK_RANGE = TILE_SIZE // 2
DEFAULT_ATTACK_SPEED = 1  # attacks per sec
DEFAULT_ATTACK_WIND_UP = 0.3
DEFAULT_ATTACK_STAMINA_COST = 45  # stamina consumed per attack
DEFAULT_ATTACK_MANA_COST = 0
DEFAULT_TARGET = "( not ( " + OTHER_PREFIX + "_id = " + SELF_PREFIX + "_id ) )"
BASIC_ATTACK_TEXTURE = 'attack_circle.png'
BASIC_ATTACK_BRIGHTNESS = 256
BASIC_ATTACK_ANIMATION_PRIORITY = 1

# SpellCastable interface
DEFAULT_ABILITY_POWER = 30
DEFAULT_ABILITY_COOLDOWN = 0.3
DEFAULT_ABILITY_STAMINA_COST = 10
DEFAULT_ABILITY_MANA_COST = 10

# Defense Stats
DEFAULT_DEFENSE = 50
DEFENSE_TIMER = int(FPS / 10)
GUARD_TEXTURE = 'guard_circle.png'
GUARD_COOLDOWN = 3
GUARD_DURATION = 3

# ExplosionProjectileCastable interface
DEFAULT_PROJECTILE_COUNTDOWN = 2  # 2 secs before self-destruction
DEFAULT_PROJECTILE_SPEED = 500
FIREBALL_EXPLOSION_RANGE = TILE_SIZE // 2
FIREBALL_TEXTURE = 'fireball.png'
FIREBALL_BRIGHTNESS = 256

# Action priorities, higher priority actions will be executed first
BUFF_PRIORITY = 4
ATTACK_PRIORITY = 2
MOVE_PRIORITY = 3
DEFENSE_PRIORITY = 1
LIGHT_PRIORITY = 2
